first commit heimdal php client
DBCDK/heimdal_php_common pull request #1
Opened 2020-02-13 14:08 UTC by rikke-dbc

2020-02-17 11:04 UTC, rikke-dbc commented
Er der én af jer, der vil kigge på denne?

2020-02-18 08:13 UTC, dbclkh requested changes
Der er lige et par ting som skal rettes til. Især de $redirect variabler som risikerer at smutte.

2020-02-18 08:13 UTC, dbclkh commented on includes/heimdalCurl.inc
> +        if(empty($token)){
Mellemrum - sikkert en kopi fra MicroCURL :)

2020-02-18 08:13 UTC, dbclkh commented on includes/heimdalCurl.inc
> +            if (empty($attributes)) {
return (empty($att)) ? array() : $att...;

2020-02-18 08:13 UTC, dbclkh commented on includes/heimdalCurl.inc
> +        $this->set_url($config['heimdal_client_url'] . 'userinfo/');
Kan vi rende ind i at heimdal_client_url ikke er sat?

2020-02-18 08:13 UTC, dbclkh commented on includes/heimdalCurl.inc
> +        $client_id = $config['heimdal_client_id'];
Hvis nu $config er tomt eller ikke indeholder disse keys?

2020-02-18 08:13 UTC, dbclkh commented on includes/heimdalCurl.inc
> +        if($this->checkMe()){
Mellemrum.

2020-02-18 08:13 UTC, dbclkh commented on includes/heimdalHelpers.inc
> +    public function getConfig() {
Kommentar om metoden mangler.

2020-02-18 08:13 UTC, dbclkh commented on includes/heimdalHelpers.inc
> +    private $config;
Kommentar om variablen. Er det en streng, array eller hvad?

2020-02-18 08:13 UTC, dbclkh commented on includes/heimdalHelpers.inc
> +        $accessplatform = isset($config['heimdal_client_url']) ? $config['heimdal_client_url'] : FALSE;
$access_platform

2020-02-18 08:13 UTC, dbclkh commented on includes/heimdalHelpers.inc
> +            $heimdal_url .= $config['heimdal_client_url'] . 'oauth/authorize?response_type=code&client_id=' . $config['heimdal_client_id'] . $redirect;
Du risikerer at den $redirect variabel ikke er sat hvis ovenstående if (25-27) ikke bliver opfyldt.

2020-02-18 08:13 UTC, dbclkh commented on includes/heimdalHelpers.inc
> +            $heimdal_url .= $config['heimdal_client_url'] . 'logout/?access_token=' . $access_token . $redirect;
Du risikerer at den $redirect variabel ikke er sat hvis ovenstående if (49-51) ikke bliver opfyldt.

2020-03-02 13:29 UTC, merged